#!/usr/bin/env bash

_vlink () {
    local word=$2 \
          prev=$3 \
          pluginsDir=${VIM_PLUGINS_DIR:-$HOME/Development/code/vim-plugins}

    case $COMP_CWORD in
        1)
            COMPREPLY=( $(compgen -W "dotvim plug replug unplug" -- "$word") ) ;;
        2)
            case $prev in
                plug|replug|unplug)
                    local IFS=$'\n'
                    COMPREPLY=( $(cd "$pluginsDir" && compgen -d -- "$word") ) ;;
            esac
    esac
}

complete -o dirnames -F _vlink vlink
